name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 51821 185.189.58.71 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to production server
        run: |
          ssh -T -p 51821 root@185.189.58.71 << 'EOF'
            echo "Deploying to production server..."
            cd ~/bot_jyotish/src
            
            # Настройка Git для использования SSH
            export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519 -o IdentitiesOnly=yes"
            
            # Обновление репозитория
            git fetch origin
            git reset --hard origin/main
            
            # Активация виртуального окружения и установка зависимостей
            source .venv/bin/activate
            pip install -r requirements.txt
            
            # Перезапуск сервиса
            systemctl restart jyotish_bot.service
            echo "Deployment completed successfully!"
          EOF