name: Deploy to Production Server

on:
  push:
    branches:
      - main  # Триггер на пуши и мерджи в main ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to production server
        run: |
          ssh -T -p 51821 root@185.189.58.71 << 'EOF'
            echo "Deploying to production server..."
            cd /Users/vladratnikov/Code/bot_jyotish/src
            git pull origin main
            source .venv/bin/activate
            pip install -r requirements.txt
            systemctl restart jyotish_bot.service  # Перезапуск сервиса
          EOF